
# enable CB_ZEPHYR_MODULE
CONFIG_CB_ZEPHYR_MODULE=y

# enable CB_ERROR module to get error handling and reporting features
CONFIG_CB_ERROR=y

# enable CB_SYS module to get system check functions and LED control features
CONFIG_CB_SYS=y
# CONFIG_CB_SYS_LED_BLINK=y
CONFIG_CB_SYS_LED_HEARTBEAT=y
CONFIG_CB_SYS_LED_BPM=40

# enable CB_INFO module to get build and system information features
CONFIG_CB_INFO=y